-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 19:09:59 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema School
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema School
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `School` DEFAULT CHARACTER SET utf8 ;
USE `School` ;

-- -----------------------------------------------------
-- Table `School`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`Student` (
  `idStudent` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `DoB` VARCHAR(45) NULL,
  `DoR` VARCHAR(45) NULL,
  `standard` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`Teacher` (
  `idTeacher` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  `education` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`Subject` (
  `idSubject` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Code` VARCHAR(45) NULL,
  `Grade` VARCHAR(45) NULL,
  `Credits` VARCHAR(45) NULL,
  `Teacher_idTeacher` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`idSubject`),
  INDEX `fk_Subject_Teacher_idx` (`Teacher_idTeacher` ASC),
  INDEX `fk_Subject_Student1_idx` (`Student_idStudent` ASC),
  CONSTRAINT `fk_Subject_Teacher`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `School`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subject_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `School`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`.`TeacherSubjectMap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`TeacherSubjectMap` (
  `idTeacherSubjectMap` INT NOT NULL,
  `idTecher` VARCHAR(45) NULL,
  `idSubject` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeacherSubjectMap`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
